# Generated by Django 3.2.9 on 2021-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.DateField(blank=True),
        ),
    ]
