# Generated by Django 3.2.9 on 2021-11-21 12:29

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Author = apps.get_model("store", "Author")
    db_alias = schema_editor.connection.alias
    Author.objects.using(db_alias).bulk_create([
        Author(name="Author1", alias="au1"),
        Author(name="Author2", alias="au2"),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Author instances,
    # so reverse_func() should delete them.
    Author = apps.get_model("store", "Author")
    db_alias = schema_editor.connection.alias
    Author.objects.using(db_alias).filter(name="Author1", alias="au1").delete()
    Author.objects.using(db_alias).filter(name="Author2", alias="au2").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_author_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        # migrations.RunPython(forwards_func, reverse_func, atomic=False),
        migrations.RunPython(forwards_func, reverse_func),
    ]
