# Generated by Django 3.2.9 on 2021-11-21 12:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Author = apps.get_model("store", "Author")
    db_alias = schema_editor.connection.alias
    Author.objects.using(db_alias).bulk_create([
        Author(name="Author3", alias="au3"),
        Author(name="Author4", alias="au4"),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Author instances,
    # so reverse_func() should delete them.
    Author = apps.get_model("store", "Author")
    db_alias = schema_editor.connection.alias
    Author.objects.using(db_alias).filter(name="Author3", alias="au3").delete()
    Author.objects.using(db_alias).filter(name="Author4", alias="au4").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_alter_author_born'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
